name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_rsa -T ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOL'
            cd /home/deployer/donation-tracker

            echo "--> Pulling latest code..."
            git pull origin main

            echo "--> Stopping old containers..."
            docker-compose down

            echo "--> Building and starting new containers..."
            docker-compose up --build -d

            echo "--> Cleaning up old docker images..."
            docker image prune -af

            echo "--> Deployment successful!"
          EOL